CREATE TABLE `countries` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(3) NOT NULL COLLATE 'utf8_unicode_ci',
	`name` VARCHAR(100) NOT NULL COLLATE 'utf8_unicode_ci',
	`ordering` INT(11) NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_unicode_ci'

INSERT INTO `countries` VALUES (1, 'US', 'United States',1);
INSERT INTO `countries` VALUES (2, 'CA', 'Canada',1);
INSERT INTO `countries` VALUES (3, 'AF', 'Afghanistan',1);
INSERT INTO `countries` VALUES (4, 'AL', 'Albania',1);
INSERT INTO `countries` VALUES (5, 'DZ', 'Algeria',1);
INSERT INTO `countries` VALUES (6, 'DS', 'American Samoa',1);
INSERT INTO `countries` VALUES (7, 'AD', 'Andorra',1);
INSERT INTO `countries` VALUES (8, 'AO', 'Angola',1);
INSERT INTO `countries` VALUES (9, 'AI', 'Anguilla',1);
INSERT INTO `countries` VALUES (10, 'AQ', 'Antarctica',1);
INSERT INTO `countries` VALUES (11, 'AG', 'Antigua and/or Barbuda',1);
INSERT INTO `countries` VALUES (12, 'AR', 'Argentina',1);
INSERT INTO `countries` VALUES (13, 'AM', 'Armenia',1);
INSERT INTO `countries` VALUES (14, 'AW', 'Aruba',1);
INSERT INTO `countries` VALUES (15, 'AU', 'Australia',1);
INSERT INTO `countries` VALUES (16, 'AT', 'Austria',1);
INSERT INTO `countries` VALUES (17, 'AZ', 'Azerbaijan',1);
INSERT INTO `countries` VALUES (18, 'BS', 'Bahamas',1);
INSERT INTO `countries` VALUES (19, 'BH', 'Bahrain',1);
INSERT INTO `countries` VALUES (20, 'BD', 'Bangladesh',1);
INSERT INTO `countries` VALUES (21, 'BB', 'Barbados',1);
INSERT INTO `countries` VALUES (22, 'BY', 'Belarus',1);
INSERT INTO `countries` VALUES (23, 'BE', 'Belgium',1);
INSERT INTO `countries` VALUES (24, 'BZ', 'Belize',1);
INSERT INTO `countries` VALUES (25, 'BJ', 'Benin',1);
INSERT INTO `countries` VALUES (26, 'BM', 'Bermuda',1);
INSERT INTO `countries` VALUES (27, 'BT', 'Bhutan',1);
INSERT INTO `countries` VALUES (28, 'BO', 'Bolivia',1);
INSERT INTO `countries` VALUES (29, 'BA', 'Bosnia and Herzegovina',1);
INSERT INTO `countries` VALUES (30, 'BW', 'Botswana',1);
INSERT INTO `countries` VALUES (31, 'BV', 'Bouvet Island',1);
INSERT INTO `countries` VALUES (32, 'BR', 'Brazil',1);
INSERT INTO `countries` VALUES (33, 'IO', 'British lndian Ocean Territory',1);
INSERT INTO `countries` VALUES (34, 'BN', 'Brunei Darussalam',1);
INSERT INTO `countries` VALUES (35, 'BG', 'Bulgaria',1);
INSERT INTO `countries` VALUES (36, 'BF', 'Burkina Faso',1);
INSERT INTO `countries` VALUES (37, 'BI', 'Burundi',1);
INSERT INTO `countries` VALUES (38, 'KH', 'Cambodia',1);
INSERT INTO `countries` VALUES (39, 'CM', 'Cameroon',1);
INSERT INTO `countries` VALUES (40, 'CV', 'Cape Verde',1);
INSERT INTO `countries` VALUES (41, 'KY', 'Cayman Islands',1);
INSERT INTO `countries` VALUES (42, 'CF', 'Central African Republic',1);
INSERT INTO `countries` VALUES (43, 'TD', 'Chad',1);
INSERT INTO `countries` VALUES (44, 'CL', 'Chile',1);
INSERT INTO `countries` VALUES (45, 'CN', 'China',1);
INSERT INTO `countries` VALUES (46, 'CX', 'Christmas Island',1);
INSERT INTO `countries` VALUES (47, 'CC', 'Cocos (Keeling) Islands',1);
INSERT INTO `countries` VALUES (48, 'CO', 'Colombia',1);
INSERT INTO `countries` VALUES (49, 'KM', 'Comoros',1);
INSERT INTO `countries` VALUES (50, 'CG', 'Congo',1);
INSERT INTO `countries` VALUES (51, 'CK', 'Cook Islands',1);
INSERT INTO `countries` VALUES (52, 'CR', 'Costa Rica',1);
INSERT INTO `countries` VALUES (53, 'HR', 'Croatia (Hrvatska)',1);
INSERT INTO `countries` VALUES (54, 'CU', 'Cuba',1);
INSERT INTO `countries` VALUES (55, 'CY', 'Cyprus',1);
INSERT INTO `countries` VALUES (56, 'CZ', 'Czech Republic',1);
INSERT INTO `countries` VALUES (57, 'DK', 'Denmark',1);
INSERT INTO `countries` VALUES (58, 'DJ', 'Djibouti',1);
INSERT INTO `countries` VALUES (59, 'DM', 'Dominica',1);
INSERT INTO `countries` VALUES (60, 'DO', 'Dominican Republic',1);
INSERT INTO `countries` VALUES (61, 'TP', 'East Timor',1);
INSERT INTO `countries` VALUES (62, 'EC', 'Ecuador',1);
INSERT INTO `countries` VALUES (63, 'EG', 'Egypt',1);
INSERT INTO `countries` VALUES (64, 'SV', 'El Salvador',1);
INSERT INTO `countries` VALUES (65, 'GQ', 'Equatorial Guinea',1);
INSERT INTO `countries` VALUES (66, 'ER', 'Eritrea',1);
INSERT INTO `countries` VALUES (67, 'EE', 'Estonia',1);
INSERT INTO `countries` VALUES (68, 'ET', 'Ethiopia',1);
INSERT INTO `countries` VALUES (69, 'FK', 'Falkland Islands (Malvinas)',1);
INSERT INTO `countries` VALUES (70, 'FO', 'Faroe Islands',1);
INSERT INTO `countries` VALUES (71, 'FJ', 'Fiji',1);
INSERT INTO `countries` VALUES (72, 'FI', 'Finland',1);
INSERT INTO `countries` VALUES (73, 'FR', 'France',1);
INSERT INTO `countries` VALUES (74, 'FX', 'France, Metropolitan',1);
INSERT INTO `countries` VALUES (75, 'GF', 'French Guiana',1);
INSERT INTO `countries` VALUES (76, 'PF', 'French Polynesia',1);
INSERT INTO `countries` VALUES (77, 'TF', 'French Southern Territories',1);
INSERT INTO `countries` VALUES (78, 'GA', 'Gabon',1);
INSERT INTO `countries` VALUES (79, 'GM', 'Gambia',1);
INSERT INTO `countries` VALUES (80, 'GE', 'Georgia',1);
INSERT INTO `countries` VALUES (81, 'DE', 'Germany',1);
INSERT INTO `countries` VALUES (82, 'GH', 'Ghana',1);
INSERT INTO `countries` VALUES (83, 'GI', 'Gibraltar',1);
INSERT INTO `countries` VALUES (84, 'GR', 'Greece',1);
INSERT INTO `countries` VALUES (85, 'GL', 'Greenland',1);
INSERT INTO `countries` VALUES (86, 'GD', 'Grenada',1);
INSERT INTO `countries` VALUES (87, 'GP', 'Guadeloupe',1);
INSERT INTO `countries` VALUES (88, 'GU', 'Guam',1);
INSERT INTO `countries` VALUES (89, 'GT', 'Guatemala',1);
INSERT INTO `countries` VALUES (90, 'GN', 'Guinea',1);
INSERT INTO `countries` VALUES (91, 'GW', 'Guinea-Bissau',1);
INSERT INTO `countries` VALUES (92, 'GY', 'Guyana',1);
INSERT INTO `countries` VALUES (93, 'HT', 'Haiti',1);
INSERT INTO `countries` VALUES (94, 'HM', 'Heard and Mc Donald Islands',1);
INSERT INTO `countries` VALUES (95, 'HN', 'Honduras',1);
INSERT INTO `countries` VALUES (96, 'HK', 'Hong Kong',1);
INSERT INTO `countries` VALUES (97, 'HU', 'Hungary',1);
INSERT INTO `countries` VALUES (98, 'IS', 'Iceland',1);
INSERT INTO `countries` VALUES (99, 'IN', 'India',1);
INSERT INTO `countries` VALUES (100, 'ID', 'Indonesia',1);
INSERT INTO `countries` VALUES (101, 'IR', 'Iran (Islamic Republic of)',1);
INSERT INTO `countries` VALUES (102, 'IQ', 'Iraq',1);
INSERT INTO `countries` VALUES (103, 'IE', 'Ireland',1);
INSERT INTO `countries` VALUES (104, 'IL', 'Israel',1);
INSERT INTO `countries` VALUES (105, 'IT', 'Italy',1);
INSERT INTO `countries` VALUES (106, 'CI', 'Ivory Coast',1);
INSERT INTO `countries` VALUES (107, 'JM', 'Jamaica',1);
INSERT INTO `countries` VALUES (108, 'JP', 'Japan',1);
INSERT INTO `countries` VALUES (109, 'JO', 'Jordan',1);
INSERT INTO `countries` VALUES (110, 'KZ', 'Kazakhstan',1);
INSERT INTO `countries` VALUES (111, 'KE', 'Kenya',1);
INSERT INTO `countries` VALUES (112, 'KI', 'Kiribati',1);
INSERT INTO `countries` VALUES (113, 'KP', 'Korea, Democratic People''s Republic of',1);
INSERT INTO `countries` VALUES (114, 'KR', 'Korea, Republic of',1);
INSERT INTO `countries` VALUES (115, 'XK', 'Kosovo',1);

INSERT INTO `countries` VALUES (116, 'KW', 'Kuwait',1);
INSERT INTO `countries` VALUES (117, 'KG', 'Kyrgyzstan',1);
INSERT INTO `countries` VALUES (118, 'LA', 'Lao People''s Democratic Republic',1);
INSERT INTO `countries` VALUES (119, 'LV', 'Latvia',1);
INSERT INTO `countries` VALUES (120, 'LB', 'Lebanon',1);
INSERT INTO `countries` VALUES (121, 'LS', 'Lesotho',1);
INSERT INTO `countries` VALUES (122, 'LR', 'Liberia',1);
INSERT INTO `countries` VALUES (123, 'LY', 'Libyan Arab Jamahiriya',1);
INSERT INTO `countries` VALUES (124, 'LI', 'Liechtenstein',1);
INSERT INTO `countries` VALUES (125, 'LT', 'Lithuania',1);
INSERT INTO `countries` VALUES (126, 'LU', 'Luxembourg',1);
INSERT INTO `countries` VALUES (127, 'MO', 'Macau',1);
INSERT INTO `countries` VALUES (128, 'MK', 'Macedonia',1);
INSERT INTO `countries` VALUES (129, 'MG', 'Madagascar',1);
INSERT INTO `countries` VALUES (130, 'MW', 'Malawi',1);
INSERT INTO `countries` VALUES (131, 'MY', 'Malaysia',1);
INSERT INTO `countries` VALUES (132, 'MV', 'Maldives',1);
INSERT INTO `countries` VALUES (133, 'ML', 'Mali',1);
INSERT INTO `countries` VALUES (134, 'MT', 'Malta',1);
INSERT INTO `countries` VALUES (135, 'MH', 'Marshall Islands',1);
INSERT INTO `countries` VALUES (136, 'MQ', 'Martinique',1);
INSERT INTO `countries` VALUES (137, 'MR', 'Mauritania',1);
INSERT INTO `countries` VALUES (138, 'MU', 'Mauritius',1);
INSERT INTO `countries` VALUES (139, 'TY', 'Mayotte',1);
INSERT INTO `countries` VALUES (140, 'MX', 'Mexico',1);
INSERT INTO `countries` VALUES (141, 'FM', 'Micronesia, Federated States of',1);
INSERT INTO `countries` VALUES (142, 'MD', 'Moldova, Republic of',1);
INSERT INTO `countries` VALUES (143, 'MC', 'Monaco',1);
INSERT INTO `countries` VALUES (144, 'MN', 'Mongolia',1);
INSERT INTO `countries` VALUES (145, 'ME', 'Montenegro',1);
INSERT INTO `countries` VALUES (146, 'MS', 'Montserrat',1);
INSERT INTO `countries` VALUES (147, 'MA', 'Morocco',1);
INSERT INTO `countries` VALUES (148, 'MZ', 'Mozambique',1);
INSERT INTO `countries` VALUES (149, 'MM', 'Myanmar',1);
INSERT INTO `countries` VALUES (150, 'NA', 'Namibia',1);
INSERT INTO `countries` VALUES (151, 'NR', 'Nauru',1);
INSERT INTO `countries` VALUES (152, 'NP', 'Nepal',1);
INSERT INTO `countries` VALUES (153, 'NL', 'Netherlands',1);
INSERT INTO `countries` VALUES (154, 'AN', 'Netherlands Antilles',1);
INSERT INTO `countries` VALUES (155, 'NC', 'New Caledonia',1);
INSERT INTO `countries` VALUES (156, 'NZ', 'New Zealand',1);
INSERT INTO `countries` VALUES (157, 'NI', 'Nicaragua',1);
INSERT INTO `countries` VALUES (158, 'NE', 'Niger',1);
INSERT INTO `countries` VALUES (159, 'NG', 'Nigeria',1);
INSERT INTO `countries` VALUES (160, 'NU', 'Niue',1);
INSERT INTO `countries` VALUES (161, 'NF', 'Norfork Island',1);
INSERT INTO `countries` VALUES (162, 'MP', 'Northern Mariana Islands',1);
INSERT INTO `countries` VALUES (163, 'NO', 'Norway',1);
INSERT INTO `countries` VALUES (164, 'OM', 'Oman',1);
INSERT INTO `countries` VALUES (165, 'PK', 'Pakistan',1);
INSERT INTO `countries` VALUES (166, 'PW', 'Palau',1);
INSERT INTO `countries` VALUES (167, 'PA', 'Panama',1);
INSERT INTO `countries` VALUES (168, 'PG', 'Papua New Guinea',1);
INSERT INTO `countries` VALUES (169, 'PY', 'Paraguay',1);
INSERT INTO `countries` VALUES (170, 'PE', 'Peru',1);
INSERT INTO `countries` VALUES (171, 'PH', 'Philippines',1);
INSERT INTO `countries` VALUES (172, 'PN', 'Pitcairn',1);
INSERT INTO `countries` VALUES (173, 'PL', 'Poland',1);
INSERT INTO `countries` VALUES (174, 'PT', 'Portugal',1);
INSERT INTO `countries` VALUES (175, 'PR', 'Puerto Rico',1);
INSERT INTO `countries` VALUES (176, 'QA', 'Qatar',1);
INSERT INTO `countries` VALUES (177, 'RE', 'Reunion',1);
INSERT INTO `countries` VALUES (178, 'RO', 'Romania',1);
INSERT INTO `countries` VALUES (179, 'RU', 'Russian Federation',1);
INSERT INTO `countries` VALUES (180, 'RW', 'Rwanda',1);
INSERT INTO `countries` VALUES (181, 'KN', 'Saint Kitts and Nevis',1);
INSERT INTO `countries` VALUES (182, 'LC', 'Saint Lucia',1);
INSERT INTO `countries` VALUES (183, 'VC', 'Saint Vincent and the Grenadines',1);
INSERT INTO `countries` VALUES (184, 'WS', 'Samoa',1);
INSERT INTO `countries` VALUES (185, 'SM', 'San Marino',1);
INSERT INTO `countries` VALUES (186, 'ST', 'Sao Tome and Principe',1);
INSERT INTO `countries` VALUES (187, 'SA', 'Saudi Arabia',1);
INSERT INTO `countries` VALUES (188, 'SN', 'Senegal',1);
INSERT INTO `countries` VALUES (189, 'RS', 'Serbia',1);
INSERT INTO `countries` VALUES (190, 'SC', 'Seychelles',1);
INSERT INTO `countries` VALUES (191, 'SL', 'Sierra Leone',1);
INSERT INTO `countries` VALUES (192, 'SG', 'Singapore',1);
INSERT INTO `countries` VALUES (193, 'SK', 'Slovakia',1);
INSERT INTO `countries` VALUES (194, 'SI', 'Slovenia',1);
INSERT INTO `countries` VALUES (195, 'SB', 'Solomon Islands',1);
INSERT INTO `countries` VALUES (196, 'SO', 'Somalia',1);
INSERT INTO `countries` VALUES (197, 'ZA', 'South Africa',1);
INSERT INTO `countries` VALUES (198, 'GS', 'South Georgia South Sandwich Islands',1);
INSERT INTO `countries` VALUES (199, 'ES', 'Spain',1);
INSERT INTO `countries` VALUES (200, 'LK', 'Sri Lanka',1);
INSERT INTO `countries` VALUES (201, 'SH', 'St. Helena',1);
INSERT INTO `countries` VALUES (202, 'PM', 'St. Pierre and Miquelon',1);
INSERT INTO `countries` VALUES (203, 'SD', 'Sudan',1);
INSERT INTO `countries` VALUES (204, 'SR', 'Suriname',1);
INSERT INTO `countries` VALUES (205, 'SJ', 'Svalbarn and Jan Mayen Islands',1);
INSERT INTO `countries` VALUES (206, 'SZ', 'Swaziland',1);
INSERT INTO `countries` VALUES (207, 'SE', 'Sweden',1);
INSERT INTO `countries` VALUES (208, 'CH', 'Switzerland',1);
INSERT INTO `countries` VALUES (209, 'SY', 'Syrian Arab Republic',1);
INSERT INTO `countries` VALUES (210, 'TW', 'Taiwan',1);
INSERT INTO `countries` VALUES (211, 'TJ', 'Tajikistan',1);
INSERT INTO `countries` VALUES (212, 'TZ', 'Tanzania, United Republic of',1);
INSERT INTO `countries` VALUES (213, 'TH', 'Thailand',1);
INSERT INTO `countries` VALUES (214, 'TG', 'Togo',1);
INSERT INTO `countries` VALUES (215, 'TK', 'Tokelau',1);
INSERT INTO `countries` VALUES (216, 'TO', 'Tonga',1);
INSERT INTO `countries` VALUES (217, 'TT', 'Trinidad and Tobago',1);
INSERT INTO `countries` VALUES (218, 'TN', 'Tunisia',1);
INSERT INTO `countries` VALUES (219, 'TR', 'Turkey',1);
INSERT INTO `countries` VALUES (220, 'TM', 'Turkmenistan',1);
INSERT INTO `countries` VALUES (221, 'TC', 'Turks and Caicos Islands',1);
INSERT INTO `countries` VALUES (222, 'TV', 'Tuvalu',1);
INSERT INTO `countries` VALUES (223, 'UG', 'Uganda',1);
INSERT INTO `countries` VALUES (224, 'UA', 'Ukraine',1);
INSERT INTO `countries` VALUES (225, 'AE', 'United Arab Emirates',1);
INSERT INTO `countries` VALUES (226, 'GB', 'United Kingdom',1);
INSERT INTO `countries` VALUES (227, 'UM', 'United States minor outlying islands',1);
INSERT INTO `countries` VALUES (228, 'UY', 'Uruguay',1);
INSERT INTO `countries` VALUES (229, 'UZ', 'Uzbekistan',1);
INSERT INTO `countries` VALUES (230, 'VU', 'Vanuatu',1);
INSERT INTO `countries` VALUES (231, 'VA', 'Vatican City State',1);
INSERT INTO `countries` VALUES (232, 'VE', 'Venezuela',1);
INSERT INTO `countries` VALUES (233, 'VN', 'Vietnam',1);
INSERT INTO `countries` VALUES (234, 'VG', 'Virgin Islands (British)',1);
INSERT INTO `countries` VALUES (235, 'VI', 'Virgin Islands (U.S.)',1);
INSERT INTO `countries` VALUES (236, 'WF', 'Wallis and Futuna Islands',1);
INSERT INTO `countries` VALUES (237, 'EH', 'Western Sahara',1);
INSERT INTO `countries` VALUES (238, 'YE', 'Yemen',1);
INSERT INTO `countries` VALUES (239, 'YU', 'Yugoslavia',1);
INSERT INTO `countries` VALUES (240, 'ZR', 'Zaire',1);
INSERT INTO `countries` VALUES (241, 'ZM', 'Zambia',1);
INSERT INTO `countries` VALUES (242, 'ZW', 'Zimbabwe',1);